INSERT INTO roles (id, name)
SELECT 1, 'ADMIN'
    WHERE NOT EXISTS (SELECT 1 FROM roles WHERE id = 1);

INSERT INTO roles (id, name)
SELECT 2, 'USER'
    WHERE NOT EXISTS (SELECT 1 FROM roles WHERE id = 2);
